Implementar exportação de medicamento - BASIS-191262
BasisTI/madre pull request #286
Opened 2021-06-22 16:59 UTC by alexandreafa

2021-06-23 12:14 UTC, cedric-lamalle requested changes

2021-06-23 12:14 UTC, cedric-lamalle commented on farmacia/src/main/java/br/com/basis/madre/farmacia/service/ExportarMedicamentoService.java
> +public class ExportarMedicamentoService {
Usar injeção de dependência (colocar como `Spring Bean`).

2021-06-23 12:14 UTC, cedric-lamalle commented on farmacia/src/main/java/br/com/basis/madre/farmacia/service/ExportarMedicamentoService.java
> +    public ExportarMedicamentoService(List<Medicamento> listaMedicamentos) {
Injetar o repository e fazer a query na hora de gerar o relatório.

2021-06-23 12:14 UTC, cedric-lamalle commented on farmacia/src/main/java/br/com/basis/madre/farmacia/service/ExportarMedicamentoService.java
> +            cell.setCellValue(medicamento.getUnidade().getNome());
Usar um _DTO_ (ou uma `Map`).

2021-06-23 12:14 UTC, cedric-lamalle commented on farmacia/src/main/java/br/com/basis/madre/farmacia/web/rest/MedicamentoResource.java
> +        List<Medicamento> listarMedicamentos = medicamentoService.listarTodos();
Colocar isso no `ExportarMedicamentoService`. Lá usar paginação para não estourar a memória.

2021-06-23 14:48 UTC, alexandreafa commented on farmacia/src/main/java/br/com/basis/madre/farmacia/service/ExportarMedicamentoService.java
> +        Cell cell = row.createCell(0);
Feito.

2021-06-24 17:28 UTC, alexandreafa commented on farmacia/src/main/java/br/com/basis/madre/farmacia/service/ExportarMedicamentoService.java
> +public class ExportarMedicamentoService {
Feito.

2021-07-12 12:37 UTC, alexandreafa commented on farmacia/src/main/java/br/com/basis/madre/farmacia/service/ExportarMedicamentoService.java
> +    public ExportarMedicamentoService(List<Medicamento> listaMedicamentos) {
Feito.

2021-07-13 14:43 UTC, cedric-lamalle requested changes

2021-07-14 17:02 UTC, alexandreafa commented on farmacia/src/main/java/br/com/basis/madre/farmacia/service/ExportarMedicamentoService.java
> +        int medicamentoSize = medicamentoService.listarTodos().size();
feito

2021-07-14 17:03 UTC, alexandreafa commented on farmacia/src/main/java/br/com/basis/madre/farmacia/service/ExportarMedicamentoService.java
> +            Cell cell = row.createCell(0);
feito

2021-07-14 19:12 UTC, merged